source 'https://rubygems.org'

# Specify your gem's dependencies in jekyll-markdown-block.gemspec
group :jekyll_plugins do
  gem "jekyll-minify-html", path: "../../"
end

gem "colorator"
gem "redcarpet"
gem "jekyll", "~> 1.0.0"
